### ISSUE TITLE
improve generation of ability property for comma separated abilities

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena-scripts-builder#2]
See https://github.com/magarena/magarena/commit/a7e4beaefe9dfbb6dcce265bc7b5ac596e96bd32

**Comment by ShawnieBoy** [comment]
I've been scratching my head over this since the scriptbuilder started. My only solution would be for the keyword abilities to be integrated into the scriptbuilder. Just replacing comma's really won't work :smile:

**Comment by lodici** [comment]
Here is the code that is currently used to extract the `ability` property from the oracle text in json feed...

```
                final String ability = text
                                        .replaceAll("^\\(.+?\\)\n","")
                                        .replaceAll("^.+— ", "")
                                        .replace("\n", ";\\\n        ")
                                        .replaceAll(" \\(.+?\\)", "")
                                        .replace(getCardName(false), "SN");
```

**Comment by ShawnieBoy** [comment]
But some abilities give a list of keyword abilities to permanents.

[Akroma's Memorial](https://github.com/magarena/magarena/blob/master/release/Magarena/scripts/Akroma_s_Memorial.txt)

It's not as simple as it first looks.

**Comment by lodici** [comment]
We can now reference the Magarena core library as an external jar so _theoretically_ it should not be too difficult to access the keywords.

**Comment by melvinzhang** [comment]
I think it is better to do it in Magarena as it requires knowledge of keywords. Will look into improving the ability property parsing.

**Comment by melvinzhang** [comment]
Implemented in https://github.com/magarena/magarena/commit/27ab69c30f1fc852a1d88cc0187758a7d3776d6d

Now the engine accepts ability of the form

```
ability=Flying, first strike
```
